/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_minfo_carrepairseller_jni_JniClient */

#ifndef _Included_com_minfo_carrepairseller_jni_JniClient
#define _Included_com_minfo_carrepairseller_jni_JniClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_minfo_carrepairseller_jni_JniClient
 * Method:    GetEncodeStr
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_minfo_carrepairseller_jni_JniClient_GetEncodeStr
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_minfo_carrepairseller_jni_JniClient
 * Method:    GetDecodeStr
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_minfo_carrepairseller_jni_JniClient_GetDecodeStr
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
